### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by WangL0429** [LiuZhu-CV/BDLFusion#1]
Thank you for your nice work. May I know when the code will be released

**Comment by cenchaojun** [comment]
also wait data detail

**Comment by LiuZhu-CV** [comment]
国庆节前更新，疑问可以发邮件

**Comment by WangL0429** [comment]
Sorry to bother you again, I've written a bit of code for the training section, but I've not been able to achieve your results, looking forward to your updates!

**Comment by LiuZhu-CV** [comment]
刚赶完论文 我明天更新好 有问题加我微信吧 chinasdlz

**Comment by LiuZhu-CV** [comment]
The train codes for BDL are uploaded.
