### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by jiejiangd** [LiuZhu-CV/BDLFusion#2]
你好，想问一下方便解释一下网盘里的四个数据集吗，我看MSFD_BDL和MFNet好像是已经融合好的图像，而另外两个好像是可见光红外分开的，而且代码中M3FD文件夹中的Main文件夹中记录的训练图像好像有三千多张

**Comment by LiuZhu-CV** [comment]
M3FD和MFNet 提供的都是测试集的融合图像 因为这篇文章利用M3FD和MFNet做了后续任务

**Comment by jiejiangd** [comment]
但是这里的训练部分应该是包括融合和检测一起训练的吧

**Comment by LiuZhu-CV** [comment]
对的，我想提供下融合图像方便大家测试，这两个具体的训练集可以参考https://github.com/JinyuanLiu-CV/SegMiF https://github.com/JinyuanLiu-CV/TarDAL

**Comment by jiejiangd** [comment]
我直接在官方下载了M3FD Dataset应该是一样的吧没变动吧

**Comment by LiuZhu-CV** [comment]
没有

**Comment by jiejiangd** [comment]
好的感谢

**Comment by LiuZhu-CV** [comment]
好的 欢迎使用对比

**Comment by jiejiangd** [comment]
再问一下这个显存最低需要多少嘞，8G貌似不够，step跑到9就停了，调整了第二阶段的batch好像也不行，不然我就只能换个卡跑了

**Comment by jiejiangd** [comment]
再问一下这个显存最低需要多少嘞，8G貌似不够，step跑到9就停了，调整了第二阶段的batch好像也不行，不然我就只能换个卡跑了

**Comment by LiuZhu-CV** [comment]
8G不太够，batch size 调小点吧

**Comment by jiejiangd** [comment]
opt.batch就是二没法调，arg.batch调了好像没啥变化，一开始能跑，应该是第二阶段加了显存就停了

**Comment by LiuZhu-CV** [comment]
根据显存动态调整代码吧，我应该是没重构太好，我有空重新写训练代码

**Comment by jiejiangd** [comment]
代码中好像会用到Mask这个文件夹，但是原数据集中好像没得，这个文件夹是起到什么作用嘞

**Comment by LiuZhu-CV** [comment]
提供saliency map来监督融合训练 可从这找到https://drive.google.com/drive/folders/1WxxuXFDX4-18DfAJjDWoemREBDRcEaDH

**Comment by jiejiangd** [comment]
嗯嗯我知道可以下到，我的意思是这个saliency map是怎么您自己额外生成的吧，再遇到新的数据集也要自己生成显著图吗

**Comment by LiuZhu-CV** [comment]
嗯嗯是 也可以换其他loss ```python 
import torch
import PIL.Image as Image
import numpy as np
# import matplotlib.pyplot as plt
import os
import cv2


def pooling(mat,ksize,method='max',pad=False):
    '''Non-overlapping pooling on 2D or 3D data.

    <mat>: ndarray, input array to pool.
    <ksize>: tuple of 2, kernel size in (ky, kx).
    <method>: str, 'max for max-pooling,
                   'mean' for mean-pooling.
    <pad>: bool, pad <mat> or not. If no pad, output has size
           n//f, n being <mat> size, f being kernel size.
           if pad, output has size ceil(n/f).

    Return <result>: pooled matrix.
    '''

    m, n = mat.shape[:2]
    ky,kx=ksize

    _ceil=lambda x,y: int(np.ceil(x/float(y)))

    if pad:
        ny=_ceil(m,ky)
        nx=_ceil(n,kx)
        size=(ny*ky, nx*kx)+mat.shape[2:]
        mat_pad=np.full(size,np.nan)
        mat_pad[:m,:n,...]=mat
    else:
        ny=m//ky
        nx=n//kx
        mat_pad=mat[:ny*ky, :nx*kx, ...]

    new_shape=(ny,ky,nx,kx)+mat.shape[2:]

    if method=='max':
        result=np.nanmax(mat_pad.reshape(new_shape),axis=(1,3))
    else:
        result=np.nanmean(mat_pad.reshape(new_shape),axis=(1,3))

    return result

def calhis(img):
    ret = np.zeros(256, int)
    for i in range(img.shape[0]):
        for j in range(img.shape[1]):
            ret[img[i][j]] += 1
    return ret
def sal(his):
    ret = np.zeros(256, int)
    for i in range(256):
        for j in range(256):
            ret[i] += np.abs(j-i)*his[j]
    return ret

def vsm(img):
    his = np.zeros(256, int)
    for i in range(img.shape[0]):
        for j in range(img.shape[1]):
            his[img[i][j]] += 1
    sal = np.zeros(256, int)
    for i in range(256):
        for j in range(256):
            sal[i] += np.abs(j-i)*his[j]
    map = np.zeros_like(img, int)
    for i in range(256):
        map[np.where(img == i)] = sal[i]
    if map.max()==0:
        return np.zeros_like(img, int)
    return map / (map.max())








###############
## VSM for segmentation
##############
def map_generate2(map1,map2,c =20):
    map1_ = vsm(map1)
    map2_ = vsm(map2)
    w1 = 0.4+ (map1_*1-map2_*0.4)
    w2 = 1-w1
    return w1,w2
```
